use [RIS_DB]
insert into [Departments] (DepartmentName)
values
('Accident & Emergency'),
('Admissions'),
('Anaesthesia'),
('Breast Screening'),
('Cardiology'),
('Critical Care'),
('Day Surgery'),
('Dental'),
('Dermatology'),
('Diagnostic Imaging'),
('Endocrinology'),
('Gastroenterology'),
('General Medicine'),
('General Services'),
('General Surgery'),
('Geriatrics'),
('Gynaecology'),
('Haematology'),
('Health & Safety'),
('Hepatology'),
('Human Resources'),
('Infectious Disease'),
('Information Management'),
('Internal Medicine'),
('Laboratory Medicine'),
('Maternity'),
('Microbiology'),
('Neonatal'),
('Nephrology'),
('Neurology'),
('Neurosurgery'),
('Nutrition and Dietetics'),
('Obstetrics'),
('Occupational Therapy'),
('Oncology'),
('Ophthalmology'),
('Orthopaedics'),
('Otolaryngology'),
('Paediatrics'),
('Pain Management'),
('Pathology'),
('Patient Services'),
('Pharmacy'),
('Physiotherapy'),
('Psychiatry'),
('Purchasing & Supplies'),
('Radiology'),
('Radiotherapy'),
('Rehabilitation'),
('Renal Medicine'),
('Rheumatology'),
('Sexual Health'),
('Social Work'),
('Speech Therapy'),
('Sports Medicine'),
('Urology')
go